title: A Seated Figure's Blog
description: Interactive Software, Unresponsive Programs
me:
  link: https://github.com/distransient
  email: kel@unclear.info
default:
  links: 
    - text: Amethyst Engine
      href: https://amethyst.rs/
    - text: Contact Me! 
      href: mailto:kel@unclear.info
plugins:
  - jekyll-sitemap
